FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    lsb-release \
    software-properties-common \
    git \
    wget \
    gpg \
    ca-certificates \
    python3 \
    python3-pip \
    cmake \
    # mahimahi dependencies
    build-essential \
    protobuf-compiler \
    libprotobuf-dev \
    autotools-dev \
    iptables \
    iproute2 \
    dh-autoreconf \
    pkg-config \
    dnsmasq-base \
    apache2-bin \
    apache2-dev \
    debhelper \
    libssl-dev \
    ssl-cert \
    libxcb-present-dev \
    libcairo2-dev \
    libpango1.0-dev \
    # Added dependencies for Bazel
    curl \
    gnupg \
    apt-transport-https \
    clang \
    libicu-dev \
    lld \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Bazel
# Install Bazelisk (the official Bazel launcher) for arm64
RUN curl -fsSL -o /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-arm64 && \
    chmod +x /usr/local/bin/bazel

# Force Bazelisk to use version 8.2.1
ENV USE_BAZEL_VERSION=8.2.1

# Create a non-root user 'appuser' and add its local bin to the PATH
RUN useradd -m -s /bin/bash appuser
ENV HOME=/home/appuser
ENV PATH="$HOME/.local/bin:$PATH"

# Set up the working directory and give ownership to the new user
RUN mkdir -p /opt/ && chown -R appuser:appuser /opt/

RUN pip3 install \
    --break-system-packages \
    mysql-connector-python \
    fire \
    openai \
    pandas \
    numpy \
    tqdm

# Install Quiche
WORKDIR ${HOME}
RUN git clone --recursive https://github.com/agottipati9/quiche && \
    cd quiche && \
    CC=clang bazel build -c opt //...

WORKDIR ${HOME}
RUN git clone https://github.com/ravinet/mahimahi && \
    cd mahimahi && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install 

WORKDIR ${HOME}
